import Head from 'next/head'
import 'flowbite'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next js TS Tailwind Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Next js TS Tailwind Template</main>
    </>
  )
}
